rbac:
  create: false
  ## Use an existing ClusterRole/Role (depending on rbac.namespaced false/true)
  # useExistingRole: name-of-some-(cluster)role
  pspEnabled: false
  pspUseAppArmor: false

service:
  type: LoadBalancer
  port: 80

persistence:
  type: statefulset
  enabled: true
  storageClassName: longhorn

adminUser: admin
adminPassword: Sarita@17