apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argo-cd
spec:
  generators:
  - git:
      repoURL: https://github.com/lostinopensrc/homelab-argocd-applicationset.git
      revision: main
      files:
      - path: "tenants-discovery/tenants/**/config.json"
  template:
    metadata:
      name: '{{tenantid}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/lostinopensrc/homelab-argocd-applicationset.git
        targetRevision: main
        path: 'tenants/{{tenantid}}'
        helm:
          valueFiles:
            - {{tenantid}}.yaml
      destination:
        server: '{{cluster.address}}'
        namespace: '{{cluster.namespace}}'